name: Update List
on:
  schedule:
    - cron: '0 0 * * *' # Her gece çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python tv.py
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add DeaTHlesS-Androtv.m3u
          git commit -m "Liste Güncellendi" || exit 0
          git push
